services:
- type: web
  name: api-skin-cancer
  runtime: python
  repo: https://github.com/Safemood/api-skin-cancer
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
  autoDeployTrigger: commit
version: "1"
